export const initialFolders = [
        {
            id: "1",
            name: "Documents",
            files: [
                {
                    id: "file1",
                    name: "ProjectProposal.docx",
                    size: 1024,
                    type: "application/msword",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "doc",
                },
                {
                    id: "file2",
                    name: "BudgetPlan.xlsx",
                    size: 2048,
                    type: "application/vnd.ms-excel",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "excel",
                },
                {
                    id: "file3",
                    name: "MeetingNotes.txt",
                    size: 512,
                    type: "text/plain",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "txt",
                },
            ],
            children: [
                {
                    id: "1-1",
                    name: "Invoices",
                    files: [
                        {
                            id: "file7",
                            name: "Invoice-Jan.pdf",
                            size: 800,
                            type: "application/pdf",
                            uploadedAt: new Date().toISOString(),
                            url: "#",
                            typeofFile: "pdf",
                        },
                    ],
                    children: [],
                    parentId: "1",
                },
            ],
            parentId: null,
            isExpanded: true,
        },
        {
            id: "2",
            name: "Reports",
            files: [
                {
                    id: "file4",
                    name: "AnnualReport2024.pdf",
                    size: 1024,
                    type: "application/pdf",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "pdf",
                },
                {
                    id: "file5",
                    name: "FinancialSummary.docx",
                    size: 2048,
                    type: "application/msword",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "doc",
                },
                {
                    id: "file6",
                    name: "PerformanceMetrics.xlsx",
                    size: 4096,
                    type: "application/vnd.ms-excel",
                    uploadedAt: new Date().toISOString(),
                    url: "#",
                    typeofFile: "excel",
                },
            ],
            parentId: null,
            isExpanded: true,
        },
    ];