export const initialFolders = {
  folders: [
    {
      id: "1",
      name: "Policies",
      files: [
        {
          id: "file1",
          name: "GovernmentGuaranteePolicy2022.pdf",
          size: 1024,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Government Guarantee Policy.pdf",
          typeofFile: "pdf",
        },
         {
          id: "file2",
          name: "GuaranteePolicy2022.pdf",
          size: 1024,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Government Guarantee Policy.pdf",
          typeofFile: "pdf",
        },
          {
          id: "file3",
          name: "Policy2022.pdf",
          size: 1024,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Government Guarantee Policy.pdf",
          typeofFile: "pdf",
        },
         {
          id: "file4",
          name: "2022PolicyGovt.pdf",
          size: 1024,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Government Guarantee Policy.pdf",
          typeofFile: "pdf",
        },
      ],
      children: [
        {
          id: "1-1",
          name: "Archived Policies",
          files: [
            {
              id: "file5",
              name: "OldPolicyCircular2018.pdf",
              size: 600,
              type: "application/pdf",
              uploadedAt: new Date().toISOString(),
              url: "/files/old_policy_circular.pdf",
              typeofFile: "pdf",
            },
             {
              id: "file6",
              name: "PolicyCircular2018.pdf",
              size: 600,
              type: "application/pdf",
              uploadedAt: new Date().toISOString(),
              url: "/files/old_policy_circular.pdf",
              typeofFile: "pdf",
            },
             {
              id: "file7",
              name: "Circular2018.pdf",
              size: 600,
              type: "application/pdf",
              uploadedAt: new Date().toISOString(),
              url: "/files/old_policy_circular.pdf",
              typeofFile: "pdf",
            },
             {
              id: "file8",
              name: "2018OldPolicy.pdf",
              size: 600,
              type: "application/pdf",
              uploadedAt: new Date().toISOString(),
              url: "/files/old_policy_circular.pdf",
              typeofFile: "pdf",
            },
          ],
          children: [],
          parentId: "1",
          isExpanded: true,
        },
      ],
      parentId: null,
      isExpanded: true,
    },
    {
      id: "2",
      name: "Guidelines",
      files: [
        {
          id: "file9",
          name: "GIGW_Guidelines.pdf",
          size: 1200,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Guidelines_for_Government_websites.pdf",
          typeofFile: "pdf",
        },
          {
          id: "file10",
          name: "Guidelines.pdf",
          size: 1200,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Guidelines_for_Government_websites.pdf",
          typeofFile: "pdf",
        },
          {
          id: "file11",
          name: "Govt_guidelines.pdf",
          size: 1200,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Guidelines_for_Government_websites.pdf",
          typeofFile: "pdf",
        },
          {
          id: "file9",
          name: "Website_guidelines.pdf",
          size: 1200,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/Guidelines_for_Government_websites.pdf",
          typeofFile: "pdf",
        },
      ],
      children: [
        {
          id: "2-1",
          name: "Implementation Guides",
          files: [
            {
              id: "file10",
              name: "CyberSecurityFramework.docx",
              size: 700,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://www.energy.gov/sites/default/files/2023-05/EXEC-2022-008113%20-%20Cybersecurity%20Plan%20Templates_High%20Risk.docx",
              typeofFile: "doc",
            },
             {
              id: "file11",
              name: "SecurityFramework.docx",
              size: 700,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://www.energy.gov/sites/default/files/2023-05/EXEC-2022-008113%20-%20Cybersecurity%20Plan%20Templates_High%20Risk.docx",
              typeofFile: "doc",
            },
             {
              id: "file12",
              name: "Framework.docx",
              size: 700,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://www.energy.gov/sites/default/files/2023-05/EXEC-2022-008113%20-%20Cybersecurity%20Plan%20Templates_High%20Risk.docx",
              typeofFile: "doc",
            },
             {
              id: "file13",
              name: "WorkCyber.docx",
              size: 700,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://www.energy.gov/sites/default/files/2023-05/EXEC-2022-008113%20-%20Cybersecurity%20Plan%20Templates_High%20Risk.docx",
              typeofFile: "doc",
            },
          ],
          children: [],
          parentId: "2",
          isExpanded: true,
        },
      ],
      parentId: null,
      isExpanded: true,
    },
    {
      id: "3",
      name: "Circulars",
      files: [
        {
          id: "file14",
          name: "NDSAP Implementation Guidelines.pdf",
          size: 500,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/NDSAP Implementation Guidelines.pdf",
          typeofFile: "pdf",
        },
        {
          id: "file15",
          name: "Implementation Guidelines.pdf",
          size: 500,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/NDSAP Implementation Guidelines.pdf",
          typeofFile: "pdf",
        },
        {
          id: "file16",
          name: "Guidelines.pdf",
          size: 500,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/NDSAP Implementation Guidelines.pdf",
          typeofFile: "pdf",
        },
        {
          id: "file17",
          name: "NDSAP.pdf",
          size: 500,
          type: "application/pdf",
          uploadedAt: new Date().toISOString(),
          url: "/files/NDSAP Implementation Guidelines.pdf",
          typeofFile: "pdf",
        },
      ],
      children: [
        {
          id: "3-1",
          name: "Nomination Templates",
          files: [
            {
              id: "file18",
              name: "Nomination_Letter_Template.docx",
              size: 320,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://doiu.doi.gov/whldpdocs/Sample_Supervisor_Nomination_Letter.docx",
              typeofFile: "doc",
            },
             {
              id: "file19",
              name: "Letter_Template.docx",
              size: 320,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://doiu.doi.gov/whldpdocs/Sample_Supervisor_Nomination_Letter.docx",
              typeofFile: "doc",
            },
             {
              id: "file20",
              name: "Template.docx",
              size: 320,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://doiu.doi.gov/whldpdocs/Sample_Supervisor_Nomination_Letter.docx",
              typeofFile: "doc",
            },
             {
              id: "file19",
              name: "Nomination.docx",
              size: 320,
              type: "application/msword",
              uploadedAt: new Date().toISOString(),
              url: "https://doiu.doi.gov/whldpdocs/Sample_Supervisor_Nomination_Letter.docx",
              typeofFile: "doc",
            },
          ],
          children: [],
          parentId: "3",
          isExpanded: true,
        },
      ],
      parentId: null,
      isExpanded: true,
    },
  ],

  files: [
    {
      id: "file100",
      name: "Letter_of_DO.pdf",
      size: 2048,
      type: "application/pdf",
      uploadedAt: new Date().toISOString(),
      url: "/files/letter_of_do.pdf",
      typeofFile: "pdf",
    },
    {
      id: "file101",
      name: "SRP_Upload_Template.xlsx",
      size: 300,
      type: "application/vnd.ms-excel",
      uploadedAt: new Date().toISOString(),
      url: `https://srp.fas.gsa.gov/portal/docs/FAS%20SRP%20Excel%20Upload%20Reporting%20Template%20v1.3.9.xlsx`,
      typeofFile: "excel",
    },
    {
      id: "file102",
      name: "Readme.txt",
      size: 450,
      type: "text/plain",
      uploadedAt: new Date().toISOString(),
      url: "https://www1.ncdc.noaa.gov/pub/data/ghcn/daily/readme.txt",
      typeofFile: "txt",
    },
     {
      id: "file103",
      name: "System-Design-Document.docx",
      size: 450,
      type: "application/msword",
      uploadedAt: new Date().toISOString(),
      url: "https://www.cms.gov/Research-Statistics-Data-and-Systems/CMS-Information-Technology/TLC/Downloads/System-Design-Document.docx",
      typeofFile: "doc",
    },
  ],
};
